// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial_1.Models;

#nullable disable

namespace Parcial_1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parcial_1.Models.Marca", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaCreado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaModificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre_marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Marcas", (string)null);
                });

            modelBuilder.Entity("Parcial_1.Models.Roles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaCreado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaModificado")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Parcial_1.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<string>("clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaCreado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaModificado")
                        .HasColumnType("datetime2");

                    b.Property<int>("rolID")
                        .HasColumnType("int");

                    b.Property<int>("rolesUid")
                        .HasColumnType("int");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("rolesUid");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Parcial_1.Models.Vehiculo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<int>("anio")
                        .HasColumnType("int");

                    b.Property<int>("cantidadPuertas")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaCreado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaModificado")
                        .HasColumnType("datetime2");

                    b.Property<int>("marcaID")
                        .HasColumnType("int");

                    b.Property<string>("modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("marcaID");

                    b.ToTable("Vehiculos", (string)null);
                });

            modelBuilder.Entity("Parcial_1.Models.Venta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaCreado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaModificado")
                        .HasColumnType("datetime2");

                    b.Property<double>("totalVenta")
                        .HasColumnType("float");

                    b.Property<int>("vehiculoID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("vehiculoID");

                    b.ToTable("Ventas", (string)null);
                });

            modelBuilder.Entity("Parcial_1.Models.Usuario", b =>
                {
                    b.HasOne("Parcial_1.Models.Roles", "rolesU")
                        .WithMany()
                        .HasForeignKey("rolesUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("rolesU");
                });

            modelBuilder.Entity("Parcial_1.Models.Vehiculo", b =>
                {
                    b.HasOne("Parcial_1.Models.Marca", "marcaVeh")
                        .WithMany()
                        .HasForeignKey("marcaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("marcaVeh");
                });

            modelBuilder.Entity("Parcial_1.Models.Venta", b =>
                {
                    b.HasOne("Parcial_1.Models.Vehiculo", "vehiculoVent")
                        .WithMany()
                        .HasForeignKey("vehiculoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("vehiculoVent");
                });
#pragma warning restore 612, 618
        }
    }
}
